__include__: 'vsepp.yaml'
exp:
  outpath: logs/coco_precomp.en-jt/vsepp/
dataset:
  train:
    data: coco_precomp.en    
    workers: 0
  val: 
    data: [coco_precomp.en, jap_precomp.jt]
    workers: 0
  adapt: 
    data: [jap_precomp.en-jt]
    workers: 0
optimizer:
  name: adam
  import: lavse.optimizers.factory
  params:
    lr: 0.0006
  lr_scheduler:
    name: step
    params:
      step_size: 10000
      gamma: 0.1
  grad_clip: 2.
