exp:  
  outpath: logs_aaai/f30k_precomp/baseline/
  resume: null
dataset:
  text_repr: word
  loader_name: precomp
  vocab_paths: [.vocab_cache/f30k_precomp.json]
  train:
    data: f30k_precomp.en
    workers: 1
    batch_size: 128
  val:
    data: [f30k_precomp.en]
    workers: 1
    batch_size: 32
    limit: 5000
model:
  latent_size: 1024
  freeze_modules: [model.txt_enc.embed.glove,]
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: .vocab_cache/glove_840B_f30k_precomp.json.pkl
      add_rand_embed: true
    pooling: lens
    devices:
    - cuda
  img_enc:
    name: simple
    params:
      img_dim: 2048
    devices:
    - cuda
    pooling: mean
  similarity:
    name: cosine
    params:
      device: cuda
    device: cuda
criterion:
  name: contrastive
  params:
    margin: 0.2
    max_violation: false
    weight: 1.0
    beta: 0.991
engine:
  eval_before_training: false
  debug: false
  print_freq: 50
  nb_epochs: 100
  early_stop: 50
  valid_interval: 500
misc:
  cuda: true
  distributed: false
  seed: 1337
optimizer:
  name: adamax
  params:
    lr: 0.001
    gradual_warmup_steps: [0.5, 2.0, 20000] #torch.linspace
    lr_decay_epochs: [40000, 80000, 8000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
  grad_clip: 2.
