__include__: 'dyn.yaml'
exp:
  outpath: logs_aaai/coco_precomp.en/dyn-adamax/lr-7e-4
dataset:
  vocab_paths: [.vocab_cache/coco_precomp.json]
  train:
    data: coco_precomp.en
    batch_size: 128
    workers: 0
  val: 
    data: [coco_precomp.en]
    workers: 0
  adapt:
    data: []
optimizer:
  name: adamax
  params:
    lr: 0.0007
    gradual_warmup_steps: [0.5, 2.0, 16000] #torch.linspace
    lr_decay_epochs: [40000, 80000, 8000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
  grad_clip: 2.
model:
  latent_size: 1024  
  txt_enc:
    params:      
      glove_path: .vocab_cache/glove_840B_coco_precomp.json.pkl
