__include__: 'dyn.yaml'
exp:
  outpath: logs_aaai/f30k_precomp.en/dyn-adamax-kernel1/
dataset:
  vocab_paths: [.vocab_cache/f30k_precomp.json]
  train:
    data: f30k_precomp.en
    workers: 1
    batch_size: 115
  val:
    data: [f30k_precomp.en]
    workers: 1
    batch_size: 32
    limit: 5000
optimizer:
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 3000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
model:
  latent_size: 1024  
  txt_enc:
    params:      
      glove_path: .vocab_cache/glove_840B_f30k_precomp.json.pkl
