exp:
  outpath: runs/temp/scan_adapt/glove-adamax/
  resume: null
dataset:  
  vocab_paths: [.vocab_cache/f30k_precomp.json,]
  text_repr: word
  loader_name: precomp
  train:
    workers: 1
    batch_size: 115
    data: f30k_precomp.en
  val:
    workers: 1
    batch_size: 64
    data: [f30k_precomp.en]
  adapt:
    workers: 1
    batch_size: 128
    data: []
model:
  latent_size: 1024
  freeze_modules: []  
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: '.vocab_cache/glove_840B_f30k_precomp.json.pkl'
      add_rand_embed: True
    pooling: none
    devices: [cuda,]
  img_enc:
    name: scan
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: none    
  similarity:
    name: scan_adapt
    params:
      device: cuda # FIXME
      feature_norm: clipped_l2norm
      smooth: 4
      agg_function: Mean
    device: cuda # FIXME
  ml_similarity: null
criterion:
  margin: 0.2
  max_violation: False
  beta: 0.991
ml_criterion:
  margin: 0.2
  max_violation: False
  beta: 0.991
optimizer:
  name: adamax
  params:
    lr: 0.001
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 3000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
engine:
  eval_before_training: False
  debug: False
  print_freq: 10
  nb_epochs: 100
  early_stop: 50
  valid_interval: 500
misc: # TODO
  cuda: True
  distributed: False # TODO 
  seed: 1337 # TODO
