__include__: 'scan.yaml'
exp:
  outpath: logs/coco_precomp.en/scan/
dataset:
  train:
    data: coco_precomp.en
    workers: 0
  val: 
    data: [coco_precomp.en]
    workers: 0
  adapt:
    data: []
optimizer:
  params:
    lr: .0005
  lr_scheduler: 
    params:
      step_size: 32800
      gamma: 0.1
