exp:
  resume: null # last, best_[...], or empty (from scratch)
dataset:  
  vocab_paths: [.vocab_cache/f30k_precomp.json,]
  text_repr: word
  loader_name: precomp
  train:
    data: f30k_precomp.en
    workers: 1
    batch_size: 128
  val: 
    data: [f30k_precomp.en]
    workers: 1
    batch_size: 32
    limit: 5000
model:
  latent_size: 1024
  freeze_modules: [] # TODO: implement
  # freeze_modules: [txt_enc.embedding, img_enc.cnn]  
  txt_enc:
    name: gru
    params:
      embed_dim: 300
      use_bi_gru: true
    pooling: lens
    devices: [cuda,]
  img_enc:
    name: vsepp_precomp
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: mean
  similarity:
    name: cosine
    params:
      device: cuda # FIXME
    device: cuda # FIXME
criterion:
  margin: 0.2
  max_violation: False
  beta: 0.991
optimizer:
  import: lavse.optimizers.factory
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 2000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
engine:
  eval_before_training: False
  debug: False
  print_freq: 10
  nb_epochs: 22
  early_stop: 50
  valid_interval: 500
misc: # TODO
  cuda: True
  distributed: False # TODO 
  seed: 1337 # TODO
