__include__: abstract.yaml
exp:
  outpath: logs/coco_precomp/adapt_t2i/glove-realfreeze-img_norm_softmax-lr5e-4/
  resume: null # last, best_[...], or empty (from scratch)
dataset:
  vocab_paths: [.vocab_cache/coco_precomp.json]
  train:
    data: coco_precomp.en
    batch_size: 128
    workers: 0
  val: 
    data: [coco_precomp.en]
    workers: 0
  adapt:
    data: []
model:
  latent_size: 1024
  freeze_modules: [model.txt_enc.embed.glove,]
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: '.vocab_cache/glove_coco_precomp.json.pkl'
      add_rand_embed: true
    pooling: none
    devices: [cuda,]
  img_enc:
    name: simple
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: none
  similarity:
    name: adapt_t2i
    params:
      latent_size: 1024
      k: 1      
      norm_output: True
      gamma: 10
      device: cuda # FIXME
    device: cuda # FIXME
optimizer:
  name: adamax
  params:
    lr: 0.0005
    gradual_warmup_steps: [0.5, 2.0, 16000] #torch.linspace
    lr_decay_epochs: [40000, 80000, 8000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
