__include__: 'liwe.yaml'
exp:
  outpath: logs/jap_precomp.jt/liwe-lr2e-4/
dataset:
  train:
    data: jap_precomp.jt
  val: 
    data: [jap_precomp.jt]
  adapt:
    data: []
optimizer:
  name: adam
  import: lavse.optimizers.factory
  params:
    lr: 0.0002
  lr_scheduler:
    name: step
    params:
      step_size: 7600
      gamma: 0.1
  grad_clip: 2.
