exp:
  outpath: runs/temp/dyn_t2i_kernel_5/
  resume: null # last, best_[...], or empty (from scratch)
dataset:  
  vocab_paths: [.vocab_cache/f30k_precomp.json]
  text_repr: word
  loader_name: precomp
  train:
    data: f30k_precomp.en
    workers: 1
    batch_size: 128
  val: 
    data: [f30k_precomp.en]
    workers: 1
    batch_size: 32
    limit: 5000
model:
  latent_size: 1024
  freeze_modules: []
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: '.vocab_cache/glove_840B_f30k_precomp.json.pkl'
      add_rand_embed: True
    pooling: none
    devices: [cuda,]
  img_enc:
    name: simple
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: none
  similarity:
    name: projconv_t2i
    params:
      latent_size: 1024
      reduce_proj: 8
      groups: 1024
      img_dim: 2048
      kernel_size: 5
      padding: 1
      # k: 8      
      device: cuda # FIXME
    device: cuda # FIXME
  ml_similarity: null
criterion:
  name: contrastive
  params:    
    margin: 0.2
    max_violation: false
    weight: 1.
    beta: 0.991
optimizer:  
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 2000] #range
    lr_decay_rate: .50
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
engine:
  eval_before_training: False
  debug: False
  print_freq: 50
  nb_epochs: 100
  early_stop: 50
  valid_interval: 500
misc: # TODO
  cuda: True
  distributed: False # TODO 
  seed: 1337 # TODO
