dataset:  
  vocab_path: .vocab_cache/f30k_precomp.json
  text_repr: word
  loader_name: precomp
  train:
    data: f30k_precomp.en
    workers: 1
    batch_size: 128
  val: 
    data: [f30k_precomp.en]
    workers: 1
    batch_size: 32
    limit: 5000
