__include__: abstract.yaml
exp:
  outpath: runs/coco_precomp/txt:glove_img:hierarchical/
  resume: null # last, best_[...], or empty (from scratch)
dataset:  
  vocab_path: .vocab_cache/coco_precomp.json
  text_repr: word
  loader_name: precomp
  train:
    data: coco_precomp.en
    workers: 0
    batch_size: 128
  val: 
    data: [coco_precomp.en]
    workers: 0
    batch_size: 32
    limit: 5000
model:
  latent_size: 1024
  freeze_modules: [model.txt_enc.embed.glove,]
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: '.vocab_cache/glove_840B_coco_precomp.json.pkl'
      add_rand_embed: true
    pooling: lens
    devices: [cuda,]
  img_enc:
    name: hierarchical
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: mean
  similarity:
    name: cosine
    params:
      device: cuda
    device: cuda
criterion:
  margin: 0.2
  max_violation: False
  beta: 0.995
optimizer:
  name: adamax
  params:
    lr: 0.001
    gradual_warmup_steps: [0.5, 2.0, 8000] #torch.linspace
    lr_decay_epochs: [16000, 80000, 10000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
