exp:
  resume: null # last, best_[...], or empty (from scratch)
  outpath: logs/saliency-kp-i2t/
dataset:  
  vocab_paths: [.vocab_cache/f30k_precomp.json,]
  text_repr: word  
  loader_name: precomp_image    
  train:
    data: f30k
    workers: 4
    batch_size: 80
  val:
    data: [f30k]
    workers: 1
    batch_size: 64
  adapt:
    data: []
    workers: 0
    batch_size: 1
model:
  latent_size: 1024
  freeze_modules: [model.txt_enc.embed.glove,]
  txt_enc:
    name: gru_glove
    params:      
      glove_path: .vocab_cache/glove_840B_f30k_precomp.json.pkl
      embed_dim: 300
      use_bi_gru: true
    pooling: none        
    devices: [cuda,]
  img_enc:
    name: image_feat
    params:
      cnn: null
      img_dim: 2048
    pooling: none
    devices: [cuda,]
  similarity:
    name: kp_i2t
    params:
      latent_size: 1024
      reduce_proj: 16
      groups: 1024
      img_dim: 2048
      kernel_size: 1
      padding: 1
      device: cuda
    device: cuda
  criterion:
    name: contrastive
    params:
      margin: 0.2
      max_violation: false
      weight: 1.0
      beta: 0.991
optimizer:
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 3000] #range
    lr_decay_rate: .25      
  grad_clip: 1.
engine:
  eval_before_training: False
  debug: False
  print_freq: 10
  nb_epochs: 30
  early_stop: 50
  valid_interval: 500
misc: # TODO
  cuda: True
  distributed: False # TODO 
  seed: 1337 # TODO
