exp:
  outpath: logs/coco_precomp.en/liwe_glove_gru-adamax-128-256/
  resume: null # last, best_[...], or empty (from scratch)
dataset:  
  vocab_paths: [.vocab_cache/coco_precomp.json, .vocab_cache/char.json, ]
  text_repr: word
  loader_name: precomp
  train:
    data: coco_precomp.en
    workers: 0
    batch_size: 128
  val: 
    data: [coco_precomp.en]
    workers: 0
    batch_size: 32
    limit: 5000
model:
  latent_size: 1024
  freeze_modules: [model.txt_enc.glove.glove,] # TODO: implement
  # freeze_modules: [txt_enc.embedding, img_enc.cnn]  
  txt_enc:
    name: liwe_gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      liwe_neurons: [128, 256]
      glove_path: '.vocab_cache/glove_840B_coco_precomp.json.pkl'
    pooling: lens
    devices: [cuda,]
  img_enc:
    name: hierarchical
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: mean
  similarity:
    name: scan
    params:
      device: cuda # FIXME
    device: cuda # FIXME
criterion:
  margin: 0.2
  max_violation: False
  beta: 0.991
optimizer:
  name: adamax
  params:
    lr: 0.001
    gradual_warmup_steps: [0.5, 2.0, 16000] #torch.linspace
    lr_decay_epochs: [32000, 80000, 8000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
  grad_clip: 2.
engine:
  eval_before_training: True
  debug: False
  print_freq: 10
  nb_epochs: 22
  early_stop: 50
  valid_interval: 500
misc: # TODO
  cuda: True
  distributed: False # TODO 
  seed: 1337 # TODO
