__include__: 'clmr.yaml'
exp:
  outpath: logs/f30k/resnet50/clmr-adamax/
dataset:
  train:
    data: f30k
    batch_size: 128
  val: 
    data: [f30k]
  adapt:
    data: []
optimizer:
  import: lavse.optimizers.factory
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 16000] #torch.linspace
    lr_decay_epochs: [20000, 40000, 4000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
