__include__: 'liwe.yaml'
exp:
  outpath: logs/m30k_precomp.en-de/simple-liwe-adamax-/
dataset:
  train:
    data: m30k_precomp.en    
  val: 
    data: [m30k_precomp.en, m30k_precomp.de]    
  adapt: 
    data: [m30k_precomp.en-de]
model:
  latent_size: 1024
  freeze_modules: []
  txt_enc:
    name: liwe_gru
    params:
      embed_dim: 300
      liwe_neurons: [384, 448]
      liwe_activation: nn.LeakyReLU(0.1, inplace=True)
      use_bi_gru: true
    pooling: lens
    devices: [cuda,]
optimizer:
  import: lavse.optimizers.factory
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 2000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
