__include__: '../clmr.yaml'
exp:
  outpath: logs/f30k_precomp.en/ablation/beta_0999/
dataset:
  train:
    data: f30k_precomp.en
  val: 
    data: [f30k_precomp.en]
  adapt:
    data: []
model:
  latent_size: 1024
  freeze_modules: []  
  txt_enc:
    name: gru
    params:
      embed_dim: 300
      use_bi_gru: true
    pooling: lens
    devices: [cuda,]
  img_enc:
    name: hierarchical
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: mean    
  similarity:
    name: cosine
    params:
      device: cuda # FIXME
    device: cuda # FIXME
criterion:
  margin: 0.2
  max_violation: False
  beta: 0.999
optimizer:
  import: lavse.optimizers.factory
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 2000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
