__include__: 'kp.yaml'
exp:
  outpath: logs/f30k_precomp/kp-i2t/
dataset:
  vocab_paths: [.vocab_cache/f30k_precomp.json]
  train:
    data: f30k_precomp.en
    workers: 1
    batch_size: 100
  val:
    data: [f30k_precomp.en]
    workers: 1
    batch_size: 32
    limit: 5000
optimizer:
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 3000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
  grad_clip: 1.
model:
  latent_size: 1024  
  txt_enc:
    params:      
      glove_path: .vocab_cache/glove_840B_f30k_precomp.json.pkl
  similarity:
    name: kp_t2i
    params:
      latent_size: 1024
      reduce_proj: 16
      groups: 1024
      img_dim: 2048
      kernel_size: 1
      padding: 0
      norm_output: True
      gamma: 1
      train_gamma: True
      device: cuda
    device: cuda
