__include__: 'kp.yaml'
exp:
  outpath: logs/coco_precomp/kp-t2i-norm-bn-traingamma1/
dataset:
  vocab_paths: [.vocab_cache/coco_precomp.json]
  train:
    data: coco_precomp.en
    workers: 0
    batch_size: 115
  val:
    data: [coco_precomp.en]
    workers: 0
    batch_size: 32
    limit: 5000
optimizer:
  name: adamax
  params:
    lr: 0.0007
    gradual_warmup_steps: [0.5, 2.0, 16000] #torch.linspace
    lr_decay_epochs: [40000, 80000, 8000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
  grad_clip: 2.
model:
  txt_enc:
    params:      
      glove_path: .vocab_cache/glove_840B_coco_precomp.json.pkl