exp:
  resume: null
  outpath: logs/coco_precomp/kp-t2i-dynmm-bnleaky
dataset:
  text_repr: word
  loader_name: precomp
  train:
    workers: 4
    batch_size: 128
    data: coco_precomp.en
  val:
    workers: 4
    batch_size: 256
    limit: 5000
    data:
    - coco_precomp.en
  vocab_paths:
  - .vocab_cache/coco_precomp.json
model:
  latent_size: 1024
  freeze_modules: []
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: .vocab_cache/glove_840B_coco_precomp.json.pkl
      add_rand_embed: true
    pooling: none
    devices:
    - cuda
  img_enc:
    name: simple
    params:
      img_dim: 2048
    devices:
    - cuda
    pooling: none
  similarity:
    name: dyn_mm_t2i
    params:
      latent_size: 1024
      reduce_proj: 8
      groups: 1024
      img_dim: 2048
      kernel_size: 1
      padding: 0
      device: cuda
      norm_output: true
      gamma: 10
    device: cuda
  criterion:
    name: contrastive
    params:
      margin: 0.2
      max_violation: false
      weight: 1.0
      beta: 0.991
engine:
  eval_before_training: false
  debug: false
  print_freq: 100
  nb_epochs: 100
  early_stop: 50
  valid_interval: 500
misc:
  cuda: true
  distributed: false
  seed: 1337
optimizer:
  name: adamax
  params:
    lr: 0.0007
    gradual_warmup_steps: [0.5, 2.0, 16000] #torch.linspace
    lr_decay_epochs: [40000, 80000, 8000] #range 
    lr_decay_rate: .25
  lr_scheduler: 
    name: null  
  grad_clip: 2.
